---
title: "Analysis of tooth growth in guinea pigs"
author: "Srijan Nayak"
date: "08/08/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r load_libraries}
# load libraries for analysis
library(dplyr)
library(ggplot2)
```

```{r load_data}
# load the ToothGrowth data
data("ToothGrowth")
```

## Tooth length vs. supplement type and dose

Let's see how the response varies for different supplement types and dosages
with a boxplot.

```{r boxplot, fig.height=3.2}
ToothGrowth %>%
  mutate(
    dose = as.factor(dose),
    # orange juice is coded as 'OJ' and ascorbic acid is coded as 'VC'
    supp = if_else(supp == "OJ", "Orange juice", "Ascorbic acid")
  ) %>%
  ggplot() +
  geom_boxplot(aes(x = dose, y = len, color = supp)) +
  labs(title = "Effect of supplement type and dose on tooth length",
       x = "Dose", y = "Tooth length", color = "Supplement type")
```

From the above plot it seems that more dosage results in longer tooth length. It
also seems that orange juice might be a better supplement than ascorbic acid.
